print (3+4)
print (3 * 5)

print ("Hello  World");

if( 3 == 3)
{
    print ("true");
}


if( 3 == 3)
{
    print ("true");
}


string $theName = "Derples";

if ($theName =="Casie")
{
    print ("that's my name");
}
else if ($theName == "David")
{
    print ("But you have David");
}
else if ($theName == "Derples")
{
    print ("Derples is that you?");
}

else
{
    print( $theName + "? who are you");
}